PROGRAM AOC_DAY_1_1 (INFILE, OUTPUT);

TYPE
    LEFTRIGHT = (LEFT, RIGHT);
    STR255 = STRING(255);

VAR
    INFILE: TEXT;
    LINE: STR255;

    DIRECTION: LEFTRIGHT;
    COUNT: INTEGER;

    POINTER: INTEGER;
    ZERO_COUNT: INTEGER;   


FUNCTION EXTRACT_DIRECTION(LINE: STR255): LEFTRIGHT;
BEGIN
    IF LINE[1] = 'L' THEN EXTRACT_DIRECTION := LEFT
    ELSE IF LINE[1] = 'R' THEN EXTRACT_DIRECTION := RIGHT
    ELSE BEGIN
        WRITELN("BAD TRIP, MAN");
        EXTRACT_DIRECTION := LEFT;
    END;
END;


FUNCTION EXTRACT_NUMBER(LINE: STR255): INTEGER;
VAR
    NUMBER: INTEGER := 0;
    LEN: INTEGER;
    SCAN: INTEGER := 2;

BEGIN
    LEN := LENGTH(LINE);

    REPEAT
        NUMBER := NUMBER * 10;
        NUMBER := NUMBER + ORD(LINE[SCAN]) - ORD('0');
        SCAN := SCAN + 1;
    UNTIL SCAN > LEN;

    EXTRACT_NUMBER := NUMBER;
END;


(* MAIN *)
BEGIN
    RESET(INFILE);
    POINTER := 50;
    ZERO_COUNT := 0;

    REPEAT
        READLN(INFILE, LINE); 

	DIRECTION := EXTRACT_DIRECTION(LINE);
	COUNT := EXTRACT_NUMBER(LINE);

 	WHILE COUNT >= 100 DO BEGIN
            ZERO_COUNT := ZERO_COUNT + 1;
            COUNT := COUNT - 100;
	END;

        CASE DIRECTION OF
            LEFT : POINTER := POINTER - COUNT;
	    RIGHT : POINTER := POINTER + COUNT;
        END;

	IF POINTER > 99 THEN BEGIN
            POINTER := POINTER - 100; { 0...99 is 100 items }
            ZERO_COUNT := ZERO_COUNT + 1;
        END ELSE IF POINTER < 0 THEN BEGIN
            POINTER := POINTER + 100;
            if (100 - pointer) <> count then
	      ZERO_COUNT := ZERO_COUNT + 1;
        END ELSE IF POINTER = 0 THEN BEGIN
            ZERO_COUNT := ZERO_COUNT + 1;
        END;

        WRITELN("------");
        WRITELN("Line: ", LINE);
        WRITELN("Pointer: ", POINTER);
        WRITELN("Zero count: ", ZERO_COUNT);

    UNTIL EOF(INFILE);
    WRITELN(ZERO_COUNT);
END.
